import { Trip, Profile, Vehicle, DeliveryRequest, Booking, AppNotification, CargoCategory } from '../types';

export const ALL_CARGO_CATEGORIES: CargoCategory[] = [
  'Electronics & Appliances',
  'Textiles & Garments',
  'Automotive Parts & Tyres',
  'Industrial Machinery & Equipment',
  'Furniture & Home Decor',
  'Chemicals & Fertilizers',
  'Building & Construction Materials',
  'Pharmaceuticals & Medical Supplies',
  'FMCG & Packaged Foods',
  'Agricultural Produce & Grains',
  'Perishables & Dairy',
  'Hardware & Electricals',
  'Books & Stationery',
  'Documents & Legal Parcels',
  'Plastics & Rubber Goods',
  'Metal & Steel Fabrication',
  'Solar Panels & Clean Tech',
  'General Commercial Goods',
  'Other / Miscellaneous',
];

export const MOCK_DRIVERS: Profile[] = [
  {
    id: 'driver-1',
    full_name: 'Rajesh Kumar Verma',
    email: 'rajesh.verma@cargomatch.in',
    phone: '+91 98490 12345',
    role: 'driver',
    profile_image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 4.9,
    total_deliveries: 128,
    created_at: '2025-10-12T08:00:00Z',
  },
  {
    id: 'driver-2',
    full_name: 'Suresh Reddy',
    email: 'suresh.reddy@cargomatch.in',
    phone: '+91 98850 54321',
    role: 'driver',
    profile_image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 4.8,
    total_deliveries: 94,
    created_at: '2025-11-05T09:30:00Z',
  },
  {
    id: 'driver-3',
    full_name: 'Mohammad Imran',
    email: 'm.imran@cargomatch.in',
    phone: '+91 97001 98765',
    role: 'driver',
    profile_image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 4.7,
    total_deliveries: 62,
    created_at: '2025-12-01T11:00:00Z',
  },
  {
    id: 'driver-4',
    full_name: 'Anil Rao Kulkarni',
    email: 'anil.kulkarni@cargomatch.in',
    phone: '+91 99123 45678',
    role: 'driver',
    profile_image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    rating: 4.95,
    total_deliveries: 215,
    created_at: '2025-09-15T07:00:00Z',
  },
];

export const MOCK_CUSTOMERS: Profile[] = [
  {
    id: 'cust-1',
    full_name: 'Pooja Sundaram (TechHub Solutions)',
    email: 'pooja@techhub.in',
    phone: '+91 94401 22334',
    role: 'customer',
    rating: 4.9,
    total_deliveries: 18,
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'cust-2',
    full_name: 'Vikram Mehta (Apex Hardware)',
    email: 'vikram.mehta@apex.com',
    phone: '+91 98220 88990',
    role: 'customer',
    rating: 5.0,
    total_deliveries: 34,
    created_at: '2026-01-15T14:20:00Z',
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    driver_id: 'driver-1',
    vehicle_type: 'Tata Ace',
    body_type: 'Closed Container',
    registration_number: 'TS 09 UA 4421',
    total_capacity: 750,
    length_ft: 7,
    width_ft: 4.5,
    height_ft: 4.5,
    created_at: '2025-10-12T08:30:00Z',
  },
  {
    id: 'veh-2',
    driver_id: 'driver-2',
    vehicle_type: 'Mahindra Bolero Maxi Truck',
    body_type: 'Open Body',
    registration_number: 'KA 01 MG 8912',
    total_capacity: 1250,
    length_ft: 8.5,
    width_ft: 5.2,
    height_ft: 5,
    created_at: '2025-11-05T10:00:00Z',
  },
  {
    id: 'veh-3',
    driver_id: 'driver-3',
    vehicle_type: 'Pickup 8ft',
    body_type: 'Open Body',
    registration_number: 'AP 16 TX 3319',
    total_capacity: 1000,
    length_ft: 8,
    width_ft: 5,
    height_ft: 4.8,
    created_at: '2025-12-01T11:30:00Z',
  },
  {
    id: 'veh-4',
    driver_id: 'driver-4',
    vehicle_type: 'Mini Van Express',
    body_type: 'Closed Container',
    registration_number: 'TS 07 HK 9022',
    total_capacity: 600,
    length_ft: 6.5,
    width_ft: 4.2,
    height_ft: 4,
    created_at: '2025-09-15T07:30:00Z',
  },
];

export const MOCK_TRIPS: Trip[] = [
  {
    id: 'trip-1',
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    vehicle_id: 'veh-1',
    vehicle: MOCK_VEHICLES[0],
    source: 'Hyderabad',
    destination: 'Bengaluru',
    departure_time: 'Today, 06:30 AM',
    estimated_arrival: 'Today, 05:00 PM',
    total_capacity: 750,
    available_capacity: 450,
    price: 520, // Return trip discount applied (570 km)
    is_return_trip: true,
    status: 'ACTIVE',
    notes: 'Direct highway run via NH44. 450 kg clean closed container payload space available.',
    created_at: '2026-08-20T10:00:00Z',
  },
  {
    id: 'trip-1b',
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    vehicle_id: 'veh-1',
    vehicle: MOCK_VEHICLES[0],
    source: 'Bengaluru',
    destination: 'Chennai',
    departure_time: 'Tomorrow, 07:00 AM',
    estimated_arrival: 'Tomorrow, 02:30 PM',
    total_capacity: 750,
    available_capacity: 600,
    price: 480, // Standard one-way corridor (350 km)
    is_return_trip: false,
    status: 'ACTIVE',
    notes: 'Express transit via Hosur & Krishnagiri. Weather-sealed closed container.',
    created_at: '2026-08-21T08:00:00Z',
  },
  {
    id: 'trip-1c',
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    vehicle_id: 'veh-1',
    vehicle: MOCK_VEHICLES[0],
    source: 'Hyderabad',
    destination: 'Vijayawada',
    departure_time: 'In 2 days, 05:30 AM',
    estimated_arrival: 'In 2 days, 11:30 AM',
    total_capacity: 750,
    available_capacity: 350,
    price: 380, // Return trip discount (275 km)
    is_return_trip: true,
    status: 'ACTIVE',
    notes: 'Empty return run from Hyderabad industrial hub to coastal Andhra logistics hub.',
    created_at: '2026-08-21T11:00:00Z',
  },
  {
    id: 'trip-1d',
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    vehicle_id: 'veh-1',
    vehicle: MOCK_VEHICLES[0],
    source: 'Chennai',
    destination: 'Hyderabad',
    departure_time: 'In 3 days, 06:00 AM',
    estimated_arrival: 'In 3 days, 07:00 PM',
    total_capacity: 750,
    available_capacity: 500,
    price: 580, // Return trip discount (630 km)
    is_return_trip: true,
    status: 'ACTIVE',
    notes: 'Empty return along NH16 corridor. Clean, secure payload box.',
    created_at: '2026-08-22T06:00:00Z',
  },
  {
    id: 'trip-1e',
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    vehicle_id: 'veh-1',
    vehicle: MOCK_VEHICLES[0],
    source: 'Hyderabad',
    destination: 'Pune',
    departure_time: 'In 5 days, 04:30 AM',
    estimated_arrival: 'In 5 days, 04:00 PM',
    total_capacity: 750,
    available_capacity: 700,
    price: 790, // Standard one-way trip (560 km)
    is_return_trip: false,
    status: 'SCHEDULED',
    notes: 'Commercial hardware and electronics route via Solapur highway.',
    created_at: '2026-08-22T12:00:00Z',
  },
  {
    id: 'trip-2',
    driver_id: 'driver-2',
    driver: MOCK_DRIVERS[1],
    vehicle_id: 'veh-2',
    vehicle: MOCK_VEHICLES[1],
    source: 'Hyderabad',
    destination: 'Vijayawada',
    departure_time: 'Tomorrow, 08:00 PM',
    estimated_arrival: 'Day after tomorrow, 02:30 AM',
    total_capacity: 1250,
    available_capacity: 800,
    price: 680,
    is_return_trip: false,
    status: 'SCHEDULED',
    notes: 'Open body Bolero Maxi Truck. Heavy machinery, construction & hardware items accepted.',
    created_at: '2026-08-21T12:00:00Z',
  },
  {
    id: 'trip-3',
    driver_id: 'driver-3',
    driver: MOCK_DRIVERS[2],
    vehicle_id: 'veh-3',
    vehicle: MOCK_VEHICLES[2],
    source: 'Hyderabad',
    destination: 'Chennai',
    departure_time: 'In 2 days, 05:00 AM',
    estimated_arrival: 'In 2 days, 07:00 PM',
    total_capacity: 1000,
    available_capacity: 550,
    price: 620,
    is_return_trip: true,
    status: 'SCHEDULED',
    notes: 'Empty return trip. Open body pickup with weather cover tarp.',
    created_at: '2026-08-21T14:30:00Z',
  },
  {
    id: 'trip-4',
    driver_id: 'driver-4',
    driver: MOCK_DRIVERS[3],
    vehicle_id: 'veh-4',
    vehicle: MOCK_VEHICLES[3],
    source: 'Hyderabad',
    destination: 'Mumbai',
    departure_time: 'In 3 days, 04:00 AM',
    estimated_arrival: 'In 3 days, 09:30 PM',
    total_capacity: 600,
    available_capacity: 350,
    price: 1150,
    is_return_trip: false,
    status: 'SCHEDULED',
    notes: 'Express mini van route. Weather-sealed closed container, padded interior.',
    created_at: '2026-08-22T06:00:00Z',
  },
];

export const MOCK_REQUESTS: DeliveryRequest[] = [
  {
    id: 'req-101',
    customer_id: 'cust-1',
    customer: MOCK_CUSTOMERS[0],
    source: 'Hyderabad',
    destination: 'Bengaluru',
    pickup_address: 'Flat 402, Building A, Madhapur, Hyderabad, Telangana - 500081',
    pickup_address_details: {
      flat_building: 'Flat 402, Building A',
      street_area: 'Hitec City Phase 2, Madhapur',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
    },
    delivery_address: 'Plot 7B, Koramangala Industrial Area, Bengaluru, Karnataka - 560034',
    delivery_address_details: {
      flat_building: 'Plot 7B',
      street_area: '7th Block, Koramangala Industrial Area',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560034',
    },
    cargo_name: '5 kg Electronics Components (Sensors & PCBs)',
    category: 'Electronics & Appliances',
    weight: 5,
    length: 30,
    width: 25,
    height: 20,
    quantity: 2,
    fragile: true,
    special_instructions: 'Handle with care. Anti-static packaging included.',
    pickup_date: '2026-08-23',
    delivery_date: '2026-08-24',
    status: 'BOOKED',
    created_at: '2026-08-22T09:00:00Z',
  },
  {
    id: 'req-102',
    customer_id: 'cust-2',
    customer: MOCK_CUSTOMERS[1],
    source: 'Hyderabad',
    destination: 'Bengaluru',
    pickup_address: 'Unit 12, Balanagar Industrial Estate, Hyderabad - 500037',
    delivery_address: 'Peenya Industrial Area Phase 1, Bengaluru - 560058',
    cargo_name: '40 kg Automotive Spare Parts & Gaskets',
    category: 'Automotive Parts & Tyres',
    weight: 40,
    quantity: 4,
    fragile: false,
    special_instructions: 'Keep dry. Oil-sealed carton packaging.',
    pickup_date: '2026-08-23',
    delivery_date: '2026-08-24',
    status: 'BOOKED',
    created_at: '2026-08-22T11:30:00Z',
  },
  {
    id: 'req-103',
    customer_id: 'cust-1',
    customer: MOCK_CUSTOMERS[0],
    source: 'Bengaluru',
    destination: 'Chennai',
    pickup_address: 'Warehouse 4, Electronic City Phase 1, Bengaluru - 560100',
    delivery_address: 'Ambattur Industrial Estate, Chennai - 600058',
    cargo_name: '110 kg Textiles & Garment Cartons',
    category: 'Textiles & Garments',
    weight: 110,
    quantity: 6,
    fragile: false,
    special_instructions: 'Moisture protection wrapping required.',
    pickup_date: '2026-08-24',
    delivery_date: '2026-08-25',
    status: 'BOOKED',
    created_at: '2026-08-22T14:00:00Z',
  },
  {
    id: 'req-104',
    customer_id: 'cust-2',
    customer: MOCK_CUSTOMERS[1],
    source: 'Hyderabad',
    destination: 'Vijayawada',
    pickup_address: 'Plot 88, Sanath Nagar, Hyderabad - 500018',
    delivery_address: 'Autonagar Main Road, Vijayawada - 520007',
    cargo_name: '20 kg Medical Diagnostic Supplies',
    category: 'Pharmaceuticals & Medical Supplies',
    weight: 20,
    quantity: 2,
    fragile: true,
    special_instructions: 'Keep temperature below 25C. Upright orientation.',
    pickup_date: '2026-08-25',
    delivery_date: '2026-08-25',
    status: 'OPEN',
    created_at: '2026-08-22T16:00:00Z',
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-9901',
    customer_id: 'cust-1',
    customer: MOCK_CUSTOMERS[0],
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    trip_id: 'trip-1',
    trip: MOCK_TRIPS[0],
    request_id: 'req-101',
    request: MOCK_REQUESTS[0],
    price: 520,
    match_score: 98,
    status: 'IN_TRANSIT',
    otp: '4829',
    otp_verified: false,
    payment_status: 'PAID',
    payment_method: 'UPI',
    transaction_id: 'TXN-UPI-884219',
    paid_at: '2026-08-22T09:16:00Z',
    booked_at: '2026-08-22T09:15:00Z',
  },
  {
    id: 'bk-9902',
    customer_id: 'cust-2',
    customer: MOCK_CUSTOMERS[1],
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    trip_id: 'trip-1',
    trip: MOCK_TRIPS[0],
    request_id: 'req-102',
    request: MOCK_REQUESTS[1],
    price: 680,
    match_score: 95,
    status: 'ACCEPTED',
    otp: '7391',
    otp_verified: false,
    payment_status: 'PAID',
    payment_method: 'CARD',
    transaction_id: 'TXN-CARD-941024',
    paid_at: '2026-08-22T11:45:00Z',
    booked_at: '2026-08-22T11:35:00Z',
  },
  {
    id: 'bk-9903',
    customer_id: 'cust-1',
    customer: MOCK_CUSTOMERS[0],
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    trip_id: 'trip-1b',
    trip: MOCK_TRIPS[1],
    request_id: 'req-103',
    request: MOCK_REQUESTS[2],
    price: 820,
    match_score: 94,
    status: 'PICKED_UP',
    otp: '3108',
    otp_verified: false,
    payment_status: 'PAID',
    payment_method: 'UPI',
    transaction_id: 'TXN-UPI-701945',
    paid_at: '2026-08-22T14:10:00Z',
    booked_at: '2026-08-22T14:05:00Z',
  },
  {
    id: 'bk-9904',
    customer_id: 'cust-2',
    customer: MOCK_CUSTOMERS[1],
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    trip_id: 'trip-1c',
    trip: MOCK_TRIPS[2],
    request_id: 'req-104',
    request: MOCK_REQUESTS[3],
    price: 450,
    match_score: 96,
    status: 'PENDING',
    otp: '9024',
    otp_verified: false,
    payment_status: 'PAID',
    payment_method: 'NETBANKING',
    transaction_id: 'TXN-NET-551982',
    paid_at: '2026-08-22T16:15:00Z',
    booked_at: '2026-08-22T16:05:00Z',
  },
  {
    id: 'bk-9905',
    customer_id: 'cust-1',
    customer: MOCK_CUSTOMERS[0],
    driver_id: 'driver-1',
    driver: MOCK_DRIVERS[0],
    trip_id: 'trip-1',
    trip: MOCK_TRIPS[0],
    price: 950,
    match_score: 97,
    status: 'DELIVERED',
    otp: '5512',
    otp_verified: true,
    payment_status: 'PAID',
    payment_method: 'UPI',
    transaction_id: 'TXN-UPI-418290',
    paid_at: '2026-08-21T18:00:00Z',
    booked_at: '2026-08-21T10:00:00Z',
    delivered_at: '2026-08-21T17:45:00Z',
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    user_id: 'cust-1',
    title: 'Cargo In Transit',
    message: 'Rajesh Kumar Verma has picked up your 5 kg Electronics cargo and is en route to Bengaluru.',
    read: false,
    type: 'status_update',
    created_at: '2026-08-22T10:30:00Z',
  },
  {
    id: 'notif-2',
    user_id: 'driver-1',
    title: 'New Cargo Request Accepted',
    message: 'You accepted booking #BK-9901 (5 kg Electronics) for ₹1,200.',
    read: true,
    type: 'booking',
    created_at: '2026-08-22T09:15:00Z',
  },
];

export const POPULAR_ROUTES = [
  { from: 'Hyderabad', to: 'Bengaluru', distance: '570 km', avgSavings: '42%', activeTrips: 18 },
  { from: 'Hyderabad', to: 'Vijayawada', distance: '275 km', avgSavings: '38%', activeTrips: 24 },
  { from: 'Hyderabad', to: 'Chennai', distance: '630 km', avgSavings: '45%', activeTrips: 12 },
  { from: 'Hyderabad', to: 'Mumbai', distance: '710 km', avgSavings: '35%', activeTrips: 15 },
  { from: 'Bengaluru', to: 'Hyderabad', distance: '570 km', avgSavings: '48%', activeTrips: 21 },
];
